# Generated by Django 4.1.3 on 2022-11-27 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidApp', '0002_account_mask_account_official_name_account_subtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 12, 46, 31, 285364)),
        ),
    ]
